rabbitholegg/questdk-plugins

rome.json

The Rome vscode extension appears to be sorting in a way that is different when running `rome check .` which causes linting to fail https://github.com/rabbitholegg/questdk-plugins/actions/runs/5956466719/job/16157366692#step:5:189

Fix(ci): import sorting is inconsistent

---

packages/tsconfig/base.json

Fixes our remote build issues by setting default `moduleResolution` to `node` instead of `NodeNext`

Fix(tsconfig): change base module resolution

---

.changeset/silent-rats-explode.md
packages/registry/src/index.ts

Quick fix to add stake to `executePlugin`

Add stake execution

---

.changeset/modern-days-change.md
packages/okutrade/src/utils.ts

This PR fixes an issue where some token swaps were not being detected due to a casing issues.

fix(okutrade): convert V3 token addresses to lowercase

---

.changeset/rotten-bees-battle.md
packages/gmx/src/GMX.test.ts
packages/gmx/src/GMX.ts

I left the arrays and the constants in place just so it's easy to expand support in the future.

Fix(gmx): remove V1 support

---

.changeset/neat-teachers-chew.md
packages/uniswap/src/Uniswap.test.ts
packages/uniswap/src/utils.ts

This PR fixes an issue where some token swaps were not being detected due to a casing issue.

fix(uniswap): fix casing issue with tokens on V3 swaps

---

.changeset/calm-tigers-rescue.md
packages/zora/src/Zora.ts
packages/zora/src/test-setup.ts

This pr fixes a bug in the zora plugin where token addresses are not being recognized due to a casing issue

fix(zora): fix casing issue with token addresses when using arrays

---

.changeset/dry-kiwis-speak.md
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/abi.ts

Working theory is that `tokenId` is not defined in the params for 721 collections, this means that when misconfigured a quest targetting a 721 collection with a `tokenId` set will be impossible to complete. This PR addresses that by only filtering based on `tokenId` if the function being called is on an 1155 collection. Also makes sure that the `$and` array get stripped out of the filter if it's empty.

Fix(zora): 721 vs 1155 and empty $and

---

.changeset/seven-bobcats-cover.md
packages/symbiosis/package.json
pnpm-lock.yaml

This PR pins the symbiosis-js-sdk package to version 3.0.9. This is a temporary fix until we can add support for their new contracts and abi.

chore(symbiosis): pin symbiosis sdk version

---

.changeset/shaggy-donuts-act.md
packages/mirror/src/abi.ts
packages/mirror/src/test-transactions.ts

Mirror blogs which were created past a certain point use an older function signature which was not recognized in the current implementation.
This PR adds an update to the ABI to support these mints, as well as some tests to ensure the filter is working as expected.

feat(mirror): add support for legacy mints

---

.changeset/tricky-moons-hope.md
package.json
packages/utils/package.json
packages/utils/src/constants/contract-addresses.ts
packages/utils/src/constants/index.ts
packages/utils/src/index.ts
pnpm-lock.yaml

When I moved TypeScript to root I pinned the version. I believe we were using a newer version as it wasn't pinned.
We started seeing the `dist` folder no longer having the `types` folder in it when running the `build:types` command as part of the full build pipeline. 
First thing I did was remove any * exports from utils. That got utils types building. From there I was having more issues with the registry. Same issue as utils (types folder export) only now for the plugins. Since the registry needs those types we were having issues.
In my exploration I found two related version peculiarities. We use 1.14.1 of `tslib` and 2.3.1 of `tslib` This is due to some really stale deps in some of the plugin imports. We should figure out a way to smooth out to a single version at root with overrides. …

Fix(global): Bump ts version and tweak utils exports

---

.changeset/tender-cars-walk.md
packages/boost/README.md
packages/boost/package.json
packages/boost/src/Boost.test.ts
packages/boost/src/Boost.ts
packages/boost/src/constants.ts
packages/boost/src/index.ts
packages/boost/src/test-transactions.ts
packages/boost/tsconfig.build.json
packages/boost/tsconfig.json
packages/registry/package.json
packages/registry/src/index.ts
pnpm-lock.yaml

This PR introduces the integration of the `boost` plugin for QuestDK.
Boost Protocol is a token distribution network that revolutionizes marketing and user engagement in the web3 space. It rewards users for specific onchain actions, aligning incentives between projects, investors, and participants.
This plugin targets the minting of BoostPass NFTs. BoostPass NFTs are Soul-Bound ERC-721 tokens, which means that the tokenId increments after every mint. Because of this, we do not want to filter by tokenId. There is a limit of one mint per address.
To decode the `data_` input bytes, we used the $abiParams operator to decode the recipent parameter. The `data_` input contains the recipient of the boost pass, and the referrer. Only the recipient is relevant to the plugin.
- …

feat(boost): add support for boost mint

---

.changeset/empty-mirrors-act.md
packages/mirror/src/Mirror.ts
packages/mirror/src/abi.ts
packages/registry/src/index.ts
packages/soundxyz/src/Soundxyz.ts
packages/soundxyz/src/constants.ts

Mirror is working pretty consistently. I got sound to work by hard coding the value property, but the value we're passing right now isn't working here, so sound mint embeds won't work until that's fixed. The hard coded value I had success with for [this sound](https://www.sound.xyz/notanotherbearbear/krush-sonata) was '777000000000000' but it's the _second_ param of the error that's thrown:
```
metaMessages: [
'Error: WrongPayment(uint256 paid, uint256 required)',
'                   (1500000000000000, 777000000000000)'
],
```
This `metaMessages` with the qualified error should be thrown to the FE.

Fix(sound&mirror): tweak ABIs and targets to get simulations running

---

.changeset/nine-steaks-clap.md
packages/zora/src/Zora.ts

previously Sound, Mirror, and Zora were only returning the total fees associated with a project
now, we break up fees into an object { projectFees: BigInt, actionFees: BigInt } in a non-destructive way to ensure backwards compatibility
tests written to match pattern for getProjectFees
documentation added where needed (referenced Soundxyz sdk)

getFees - break fees up into action and project

---

.github/workflows/on-push-to-main.yml
.github/workflows/verify.yml

I think we are starting to hit the 5 min timeout that we set since builds are long. Increasing this number should allow the GH Actions to have a success status without trying to exit early

chore: Increase timeout-minutes to 10

---

.changeset/smart-parents-own.md
packages/artblocks/tsconfig.build.json
packages/mirror/src/Mirror.ts
packages/soundxyz/src/Soundxyz.ts
packages/soundxyz/src/constants.ts
packages/utils/src/types/intents.ts
packages/zora/src/Zora.ts
packages/zora/src/abi.ts

So turns out sometimes if there's only 1 tier it's actually tier 1 and not tier 0.
This handles a bunch of weird edge cases for sound mint fees and zora functions when tokenId is undefined.

Feat(sound): fix mint fees

---

.changeset/soft-cougars-love.md
packages/soundxyz/src/Soundxyz.test.ts
packages/soundxyz/src/Soundxyz.ts
packages/soundxyz/src/constants.ts
packages/soundxyz/src/index.ts
packages/soundxyz/src/test-transactions.ts

This PR adds support for the legacy `SUPERMINTER` contract to pass simulations and calculate fees.

feat(sound): add support for legacy contract in simulations

---

.changeset/clean-coins-count.md
apps/create-plugin/src/viem.ts
package.json
pnpm-lock.yaml

- bumps viem version (2.7.9 -> 2.9.9)
- add blast chain to builders viem client. This allows it to look up transaction hashes on blast network.
- use Chains enum

feat(builder): add blast chain support for builder

---

.changeset/nervous-keys-design.md
packages/superbridge/src/Superbridge.ts
packages/superbridge/src/test-transactions.ts

- Fixes an issue where bridging ETH was able to pass a boost for a specific token.
It now removes any ETH based input filters if tokenAddress is an ERC20.
https://linear.app/rh-app/issue/BOOST-4002/possible-bug-in-superbridge-plugin

fix(superbridge): fix issue with invalid transactions passing

---

.github/workflows/on-push-to-main.yml

- temporary fix for consistently hitting timeouts on release step

chore: increase timeout for release step to 20 minutes

---

.changeset/gorgeous-horses-vanish.md
README.md
packages/connext/vite.config.js
packages/hop/vite.config.js
packages/mux/vite.config.js
packages/optimism/vite.config.js
packages/polygon/vite.config.js
packages/sushi/vite.config.js
packages/uniswap/vite.config.js
packages/zora/vite.config.js

up until now, we've been compiling third party sdk's as a part of our builds AND specifying them as production dependencies, which means downstream consumers are still downloading the package even though they aren't imported in the published bundle.
this change preserves imports/requires for those sdk's in our build artifacts, thereby deferring to downstream bundlers as far as how to best resolve those dependencies
the end result is faster build times, less memory overhead in ci, and smaller bundles

chore: mark third party sdks as external in build

---

.changeset/moody-yaks-rest.md
packages/utils/src/helpers/index.ts
packages/utils/src/index.ts

Exports in the utils package are not working when using namespace exports (export * from package).

fix(utils): use named imports for helpers

---

.changeset/cuddly-emus-confess.md
packages/neynar/src/Neynar.test.ts
packages/neynar/src/Neynar.ts
packages/neynar/src/types.ts
packages/utils/src/types/actions.ts

- add `fetchChannel` function
- execute `fetchChannel` and `fetchUser` in parallel for `validateFollow`
- refactor `Follow` naming to `User` name scheme to be more in line with Neynar API

feat(neynar): support usernames, channel id's as validation targets

---

.changeset/curvy-brooms-cry.md
packages/neynar/src/Neynar.test.ts
packages/neynar/src/Neynar.ts
packages/utils/src/types/actions.ts

in the event that a user and a channel have the same name, validation wouldn't work predictably.
adding a `type` field to the action params will solve this issue

feat(neynar): differentiate channel from user in follow action

---

.changeset/gold-snakes-kick.md
packages/neynar/src/Neynar.ts

calling `assert.ok` is throwing an exception at runtime, this change should unblock all farcaster action validation

fix(neynar): remove null pointer to assert.ok preventing validation

---

.changeset/lovely-llamas-float.md
packages/registry/src/index.ts
packages/utils/src/types/actions.ts

Adds a `creatorAddress` parameter to the `simulateMint` function.
This will be used in the simulateMint function as a referral address where applicable.
Related PRs:
- Sound Plugin: https://github.com/rabbitholegg/questdk-plugins/pull/436

feat(utils): pass `creatorAddress` into `simulateMint` function

---

.changeset/mighty-pianos-exercise.md
packages/soundxyz/src/Soundxyz.ts
packages/soundxyz/src/constants.ts

- Use boost `creatorAddress` as dynamic referral address for embedded mints.
- Use ZORA deployer address as a fallback if no creatorAddress is found

feat(sound): use `creatorAddress` as referral 

---

.changeset/quiet-cougars-occur.md
package.json
packages/okutrade/package.json
pnpm-lock.yaml

Recent updates to okutrades sdk have broken some tests which does not allow some GH actions to pass.
This pins the okutrade to the previous working version.
Bumps viem version from `2.13.1` --> `2.15.1`

fix(okutrade): pin okutrade dependency

---

.changeset/serious-tips-grow.md
packages/zora/src/Zora.ts

Increases the balance when running `simulateContract` to prevent the low balance `ContractFunctionExecutionError`
```
ContractFunctionExecutionError: The total cost (gas * gas fee + value) of executing this transaction exceeds the balance of the account.
```

Enable State Override

---

.changeset/poor-dragons-scream.md
packages/foundation/src/Foundation.ts

The dutch auction mechanism that is used by foundation will not be compatible, as if the price changes it will no longer be able to pass simulations as we record the fee at boost creation.
https://github.com/rabbitholegg/questdk-plugins/pull/445#issuecomment-2161740068

refactor(foundation): disable dutch-auction fee mechanism

---

.changeset/stale-horses-argue.md
packages/utils/src/helpers/mint-amount.ts

- for the formatMint function, default to 1 mint minimum when amount is undefined
- refines type

fix(utils): amount zero fix

---

.changeset/rotten-trains-fry.md
packages/soundxyz/src/Soundxyz.ts

- update to use mint amount utils

fix(sound): amount zero fix

---

.changeset/two-apricots-walk.md
packages/utils/src/types/actions.ts

- adds `referral` property to MintActionParams
https://linear.app/rh-app/issue/BOOST-4247/add-referral-as-a-mintactionparam
BOOST-4247

feat(utils): add referral property to MintActionParams

---

.changeset/kind-doors-sort.md
packages/registry/src/index.ts
packages/utils/src/types/actions.ts

- adds a `getExternalUrl` function which will (optionally) be used to generate an external url for a plugin. The Url will be generated on boost creation (w/referral atttached) instead of on the fly.
Fixes BOOST-4250

feat: Add getExternalUrl function to IActionPlugin

---

.changeset/silent-fireants-grab.md
packages/utils/src/types/intents.ts

Referral will not be used in every situation and MintIntentParams gives a type error if it is not present. Some plugins do not have a referral program, so the referral will not be used int his scenario.
This PR makes the referral param optional in the MintIntentParams type

feat(utils): allow referral to be optional in `MintIntentParams`

---

.changeset/hot-boats-help.md
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/chain-ids.ts
packages/zora/src/index.ts

- implements `getExternalUrl` function for zora
- add testing for `getExternalUrl` function
Fixes BOOST-4266
https://linear.app/rh-app/issue/BOOST-4266/implement-getexternalurl-in-plugins-zora

feat(zora): implement `getExternalUrl` function

---

.changeset/slimy-trees-wink.md
.changeset/strange-ducks-exist.md
packages/utils/src/helpers/chain-id-to-viem-chain.ts
packages/zora/package.json
packages/zora/src/Zora.ts
pnpm-lock.yaml

- updates zora protocol sdk to v 0.5.17 (later versions introduce breaking changes)
- change getSalesConfigAndTokenInfo to use updated method (fixedPrice -> salesConfig)
Tested locally against arbitrum and base sepolia boosts

chore(zora): update zora protocol sdk to v 0.5.17

---

.changeset/tame-rabbits-provide.md
packages/zora/src/Zora.ts

The `getCode` method is producing errors during simulation, so we are reverting to the previous getBytecode method.

fix(zora): change bytecode retrieval method

---

.changeset/rude-days-hide.md
packages/moshicam/src/Moshicam.test.ts
packages/moshicam/src/Moshicam.ts
packages/moshicam/src/test-transactions.ts

- fix amount zero issue
- fix linting issues in test file
- update to use mint amount utils

fix(moshicam): fix amount zero issue

---

.changeset/short-roses-pull.md
packages/fabric/src/Fabric.test.ts
packages/fabric/src/Fabric.ts
packages/fabric/src/abi.ts
packages/fabric/src/utils.ts

- add check for num tokens in validation
- fix amount zero issue
- update types
- adjust tests to catch error when no contract data is found

fix(fabric): fix amount zero issue

---

.changeset/beige-rats-reflect.md
packages/registry/src/index.ts
packages/titles/src/Titles.test.ts
packages/titles/src/Titles.ts
packages/titles/src/index.ts
packages/utils/src/types/actions.ts
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/index.ts

Some projects use multiple actionTypes, and we need a way to derive a different external url based on the actionType passed in.
Only projects needed change are Zora (Create/Mint) and TITLES (Create/Mint)
These changes will also make it easier in the future to add custom external links for defi projects which have mutiple action types available.
BOOST-4345
https://linear.app/rh-app/issue/BOOST-4345/update-externalurl-to-include-actiontype

feat: add actionType to getExternalUrl

---

.changeset/ninety-stingrays-destroy.md
packages/utils/src/types/actions.ts
packages/utils/src/types/filters.ts

on demand validation is failing when the mint action amount is an operator instead of a numeric string.
this work expands the acceptable types to handle more cases, implementing a zod schema for numeric operators

feat(utils): upgrade mint action params to support more numerical types, and operators

---

.changeset/moody-moose-shop.md
packages/titles/src/Titles.test.ts

Test is failing due to the target NFT not being mintable.
Switched the test to one that targets an NFT that is open indefinitely.
https://linear.app/rh-app/issue/BOOST-4478/fixtitles-fix-failing-simulate-mint-test
Fixes BOOST-4478

fix(titles): fix failing simulate mint test

---

.changeset/slow-peas-sit.md
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts

- Updated Zora SDK requires a tokenId on the `getToken` call, otherwise it will fail and return the base fee.
Fixes BOOST-4477
https://linear.app/rh-app/issue/BOOST-4477/zora-getfees-fails-for-1155-wo-tokenid-plugin

fix(zora): add tokenId to zora SDK getToken call for 1155s

---

.changeset/blue-pigs-visit.md
apps/create-plugin/src/questions.ts
apps/questdk/src/filter/filters.ts
apps/questdk/src/filter/index.ts
package.json
packages/balancer/src/utils.ts
packages/llama/src/Llama.ts
packages/orbit/src/utils.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/types/actions.ts
packages/utils/src/types/filters.ts
packages/utils/src/types/index.ts
packages/vela/src/utils.ts
pnpm-lock.yaml
tsconfig.json

- Implement Zod schemas for Filters in utils
- Fix several explicit any's to resolve ts issues
- Update Mint params schema to match number or FilterOperator
- Update zod to support readonly usage in abitype

Implement Zod schemas for Filters in utils [BOOST-4470]

---

.changeset/dry-ducks-sleep.md
packages/utils/src/index.ts
packages/utils/src/types/actions.ts
packages/utils/src/types/filters.ts
packages/utils/src/types/index.ts

- use `Filter` as base type for mint action params, supports any combination of:
- `FilterOperator`
- `FilterObject`
- `FilterArray`
- `Primitive`
- `PrimitiveArray`
- values of `FilterObject` and `FilterOperator` are now `Filter`, which is not a breaking change because `Filter` includes `FilterOperator`
- support wider range of filter combinations like
```{
// Logical filter operator  
"$or": [  
{
// FilterObject  
"to": {
// Logical filter operator  
"$or": [
// Primitive Array  
"0xfoo",  
"0xbar"  
]  
},
```

[BOOST-4470] Further expand filter interfaces, schemas

---

.changeset/grumpy-rice-sing.md
packages/uniswap/src/token-addresses.ts

- adds LOUDER as a swappable token

[BOOST-4537]feat(uniswap): add LOUDER to swappable token list on uniswap

---

.changeset/chilled-mayflies-poke.md
packages/coop/src/Coop.test.ts
packages/coop/src/Coop.ts

Switched from ipfs to arwevae for metadata retrieval in `getExternalUrl` function

feat(coop): use arweave for metadata retrieval
