rabbitholegg/questdk-plugins

packages/uniswap/src/UniversalRouter.ts

Fix(lint): fix uni lint error

---

packages/connext/src/Connext.test.ts
packages/connext/src/Connext.ts

The transaction shape should conform to the viem `TransactionEIP1559 ` type

Fix(Connext): Chain ID should be a number (not hex string)

---

.changeset/dirty-plums-refuse.md
packages/tally/package.json
packages/tally/src/Tally.ts
pnpm-lock.yaml

Requires https://github.com/rabbitholegg/questdk/pull/31

Fix(tally): make delegate optional

---

.changeset/nine-waves-lie.md
.github/workflows/verify.yml
packages/stargate/src/Stargate.ts

Adds ETH/WETH to supported networks and includes USDC for Optimism

Fix(stargate): Add more tokens

---

.changeset/cyan-llamas-burn.md
packages/hyphen/package.json

Unblocks build issue when trying to pull latest version

fix: remove private in order to publish

---

.changeset/flat-adults-wash.md
packages/registry/src/index.ts
packages/treasure/README.md
packages/treasure/package.json
packages/treasure/src/Treasure.test.ts
packages/treasure/src/Treasure.ts
packages/treasure/src/abi.ts
packages/treasure/src/constants.ts
packages/treasure/src/index.ts
packages/treasure/src/test-transactions.ts
packages/treasure/src/utils.ts
packages/treasure/tsconfig.build.json
packages/treasure/tsconfig.json
pnpm-lock.yaml

This PR introduces the integration of the `treasure` plugin for QuestDK and implements the swap action type for tokens.
Treasure is an Arbitrum-based web3 gaming hub that has a large ecosystem of games, items and in-game ERC-20 tokens you can earn as you play.
This plugin adds support for token swaps done using the [magicswap](https://magicswap.lol/) interface. Magic swap uses the uniswap V2 router, so implementation was very straight forward. There is support for most of the tokens available of the platform excluding VEE token. All others can be selected as token in or out (MAGIC, ANIMA, ELM, GFLY)
- `amountOut` may not be accurate due to the input data using `amountOutMin`, which takes into account the amount of slippage the user has set in the UI.

feat(treasure): add support for token swaps on magicswap

---

.changeset/dirty-crews-swim.md
packages/uniswap/package.json
packages/uniswap/src/Uniswap.test.ts
packages/uniswap/src/constants.ts
pnpm-lock.yaml

PR to exclude sepolia OP testnet from supported networks

fix(uniswap): add sepolia op testnet to excluded networks

---

.changeset/stale-needles-try.md
packages/template/src/Project.test.ts
packages/template/src/Project.ts

Refactor project template and provide a better description of how to adapt the filter function to use different action types that are available.

refactor(template): refactor project template

---

packages/utils/package.json

[There is a known issue where](https://github.com/changesets/changesets/issues/835) even though a package is private, the changeset github action will try and pull it's version and crash

Fix(utils):  version

---

.changeset/weak-monkeys-dance.md
packages/uniswap/src/token-addresses.ts

Add DEGEN token to Uniswap quest options on terminal quest create flow.
[Degen token Info](https://www.degen.tips/faq)
[Degen Contract Info](https://basescan.org/token/0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed#readContract)

Feat(uniswap): add degen

---

.changeset/tender-suns-bake.md
README.md
packages/mirror/src/Mirror.test.ts
packages/mirror/src/Mirror.ts
packages/mirror/src/abi.ts
packages/mirror/src/index.ts
packages/registry/src/index.ts
packages/utils/src/helpers/chain-id-to-viem-chain.ts
packages/utils/src/helpers/index.ts
packages/utils/src/index.ts
packages/utils/src/types/actions.ts
packages/zora/package.json
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/index.ts
pnpm-lock.yaml

This PR adds the `projectFees` for Zora and Mirror mints
Will follow up with Sound

Calculate `projectFees` for mint action type

---

.changeset/seven-dogs-do.md
packages/okutrade/src/token-addresses.ts

- adds DEGEN as a token selection for `tokenIn` or `tokenOut`
https://www.coingecko.com/en/coins/degen-base
0x4ed4e862860bed51a9570b96d89af5e1b0efefed

feat(okutrade): add DEGEN token to base

---

.changeset/great-spies-film.md
apps/questdk/package.json
apps/questdk/src/tokens/index.ts

This PR adds exports for the functions in the tokens directory and bumps the package version number.

added export for tokens directory

---

.changeset/smart-dolphins-doubt.md
packages/zora/package.json
packages/zora/src/Zora.ts
pnpm-lock.yaml

Tested via pnpm linking and confirmed that the version upgrade works

Update zora protocol sdk to `0.5.4-exports.3`

---

.changeset/strange-hornets-notice.md
apps/questdk/src/tokens/erc1155.ts
apps/questdk/src/tokens/erc721.ts

This PR fixes the token metadata functions (see [this slack thread](https://rabbithole-tam3602.slack.com/archives/C0320B5C8UB/p1709588524518149) for context)

fixed token metadata functions

---

.changeset/eleven-gorillas-walk.md
packages/zora/src/Zora.ts

Sometimes mints would fail because it is using the wrong fixed price sale strategy

fix: Use zora sdk to grab the fixed price sale strategy

---

.changeset/new-spiders-invite.md
packages/okutrade/src/test-transactions.ts
packages/okutrade/src/utils.ts

Okutrade has recently updated their api which is causing the pool lookup to fail. 
This pr updates the api call to use the new endpoint.

fix(okutrade): update getPools api call

---

.changeset/twelve-brooms-tap.md
packages/kwenta/package.json

The package will not publish to NPM with this field set to true

fix(kwenta): remove private field from package.json

---

.changeset/nice-pillows-bake.md
packages/paragraph/src/index.ts

adds helper functions to Paragraph IActionPlugin object

fix(paragraph): add helpers to plugin object

---

.changeset/four-timers-brake.md
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/abi.ts
packages/zora/src/index.ts

Fixes mint simulations in Zora plugin. 
This will now check to ensure the address is an actual contract by checking for the presence of bytecode.

fix(zora): fix issue with misconfigurations passing simulation

---

.changeset/short-pets-compete.md
apps/questdk/package.json

Removes the prepublish hook from the questdk

Chore(questdk): remove pre-publish hook

---

.changeset/ten-pugs-allow.md
apps/questdk/src/filter/filters.ts
packages/manifold/src/Manifold.ts
packages/manifold/src/utils.ts
packages/mirror/src/Mirror.test.ts
packages/mirror/src/Mirror.ts
packages/paragraph/src/Paragraph.ts
packages/pods/src/Pods.ts
packages/soundxyz/src/Soundxyz.test.ts
packages/soundxyz/src/Soundxyz.ts
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/test-setup.ts

Necessary to accommodate Decent bridged transactions

feat: make mint filters abstract

---

.changeset/afraid-houses-eat.md
package.json
packages/boost/src/Boost.test.ts
packages/boost/src/Boost.ts
packages/boost/src/types.ts
packages/utils/src/types/actions.ts
pnpm-lock.yaml

Include the tx hash and chain id to be a part of the completion payload

fix: boost plugin

---

.changeset/tender-garlics-appear.md
apps/questdk/src/constants.ts
package.json
pnpm-lock.yaml

will unblock https://github.com/rabbitholegg/questdk-plugins/pull/395
Fixes BOOST-4087

chore: upgrade viem to 2.13.1

---

.changeset/empty-fireants-switch.md
packages/uniswap/src/token-addresses.ts

Requested by Boost Creator Chat member
Token Details
https://www.geckoterminal.com/base/pools/0xb70843d66e8a0c036a12ac9701992c8a50533bbe

feat(uniswap): add ALFAA token to uniswap plugin

---

.changeset/blue-falcons-camp.md
packages/fabric/src/index.ts

Exports the additional functions needed to integrate fabric on inbox.

feat(fabric): export `getFees` and `simulateMint` function

---

.changeset/two-comics-explain.md
packages/soundxyz/src/Soundxyz.test.ts
packages/soundxyz/src/Soundxyz.ts

Updates sound to use `referral` MintActionParam as part of validation and mint simulations
fixes BOOST-4256

feat(sound): use `referral` param in validation and simulate mint

---

.changeset/lovely-pans-approve.md
packages/manifold/src/Manifold.test.ts
packages/manifold/src/Manifold.ts
packages/manifold/src/index.ts

- implement `getExternalUrl` function
- add additional tests
Fixes BOOST-4269
https://linear.app/rh-app/issue/BOOST-4269

feat(manifold): implement `getExternalUrl` function

---

.changeset/light-rabbits-develop.md
packages/pods/src/Pods.test.ts
packages/pods/src/Pods.ts
packages/pods/src/index.ts
packages/pods/src/utils.ts

- adds `getExternalUrl` function to pods plugin
- add additional tests
Fixes BOOST-4267
https://linear.app/rh-app/issue/BOOST-4267

feat(pods): implement `getExternalUrl` function

---

.changeset/fresh-buckets-float.md
packages/foundation/src/Foundation.test.ts
packages/foundation/src/Foundation.ts
packages/foundation/src/index.ts
packages/foundation/src/utils.ts

- implement `getExternalUrl` function
- add tests
BOOST-4268
https://linear.app/rh-app/issue/BOOST-4268/implement-getexternalurl-in-plugins-foundation

feat(foundation): implement `getExternalUrl` function

---

.changeset/quick-ladybugs-repair.md
packages/utils/src/constants/chain-ids.ts
packages/zora/src/Zora.test.ts
packages/zora/src/Zora.ts
packages/zora/src/chain-ids.ts

- adds support for external url generation on testnet networks sepolia and base sepolia
- adds a fallback url for unsupported chains
- add base sepolia to Chains enum (utils)

feat(zora): add support for testnet url generation

---

.changeset/rare-cats-change.md
packages/foundation/src/Foundation.ts
packages/pods/src/Pods.ts
packages/soundxyz/src/Soundxyz.ts
packages/thirdweb/src/ThirdWeb.ts
packages/utils/src/helpers/index.ts
packages/utils/src/helpers/mint-amount.ts
packages/utils/src/index.ts
packages/zora/src/Zora.ts

- rename amount utils to be more descriptive
- update references to amount utils to use more descriptive names
- add explicit check for '0' in `formatAmountToInteger`

refactor(utils): rename amount utils to be more descriptive

---

.changeset/warm-walls-unite.md

chore(titles): generate changeset

---

.changeset/shy-fans-decide.md
packages/manifold/src/Manifold.ts

- fix amount zero issue
- use mint amount utils

fix(manifold): fix amount zero issue

---

.changeset/red-peaches-raise.md
packages/basepaint/src/Basepaint.ts

fix(basepaint): fix amount zero issue

---

.changeset/itchy-shoes-cover.md
packages/basepaint/src/Basepaint.ts
packages/fabric/src/Fabric.ts
packages/manifold/src/Manifold.ts
packages/moshicam/src/Moshicam.ts

- updates name of amount utilities that were missed in the PRs for amount zero fixes.
Fixes an issue where build is failing on release.

refactor: use updated amount util functions

---

.changeset/eight-sloths-hunt.md
packages/zora/package.json
packages/zora/src/Zora.test.ts
pnpm-lock.yaml

- updates Zora SDK to newest version
- adds additional test for getting fees on the new fixed sales strategy type
- Fixes 'No Sales Config found for token' issues we were running into in the past week.

[BOOST-4572] chore(zora): update Zora SDK to 0.9.5
